name: cineandgo
description: TFG project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # A package for geodesy and geographical calculations
  latlong: ^0.6.1

  # Map to display the location cinema
  flutter_map: ^0.8.2

  # Useful date and time picker
  flutter_datetime_picker: ^1.3.5

  # Searchable dropdown list
  searchable_dropdown: ^1.1.2

  #i18n
  flutter_localizations:
    sdk: flutter

# Firebase dependencies
  # Firebase Core
  firebase_core: 0.4.4
  # Firebase Authentication
  firebase_auth: ^0.15.5+3
  # Firebase Cloud Firestore
  cloud_firestore: 0.13.4
  # Port of FirestoreUI
  firestore_ui: ^1.9.1
  

  # Google Sign In
  google_sign_in: ^4.2.0

  # Animated text kit
  animated_text_kit: ^2.0.0

  #Progress indicators & animations
  modal_progress_hud: ^0.1.3
  progress_indicators: ^0.1.4

  # Auto resize text
  auto_size_text: ^2.1.0

  # Tab indicator
  bubble_tab_indicator: ^0.1.4

  #Cool alerts
  edge_alert: ^0.0.1

  #HTTP Requests
  http: ^0.12.0+4

  #IOS stuff
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - lang/en.json
    - lang/es.json

  fonts:
    - family: OpenSans
      fonts:
      - asset: fonts/OpenSans/OpenSans-Regular.ttf
      - asset: fonts/OpenSans/OpenSans-Italic.ttf
        style: italic
      - asset: fonts/OpenSans/OpenSans-Bold.ttf
        weight: 700
